import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Form, Header, List } from '@/components'
import { useEffect, useState } from 'react'


export default function Home() {
  const [subjects, setSubjects] = useState([{
    id:"1",
    subject:"Ping Pong",
    qualification:90
  }]);

  const [values , setValues] = useState({
    id:"",
    subject:"",
    qualification:0,
    updateIndex: undefined
  })

  useEffect(()=>{
    console.log(values)
    console.log(subjects)

  },[subjects])
  return (
    <>
      <Head>
        <title>Practice Week 7</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        <div className={styles.Body}>
          <Form values={values} setValues={setValues} subjectsList={subjects} setSubjectsList={setSubjects}/>
          <List setValues={setValues} subjectsList={subjects} updateSubjects={setSubjects}/>
        </div>
      </main>
    </>
  )
}
